import Foundation

enum ShortcutError: LocalizedError {
    case writeFailed(String)

    var errorDescription: String? {
        switch self {
        case .writeFailed(let detail):
            "Couldn't create the shortcut: \(detail)"
        }
    }
}

/// Writes a double-clickable `.app` bundle that launches a game with the
/// exact Wine binary + environment Fable would use (from a `LaunchPlan`).
///
/// It's a *snapshot*: the resolved env (WINEPREFIX, D3DMetal paths, DLL
/// overrides, …) is baked into the bundle's launch script. If the bottle's
/// backend or Fable's component paths change, regenerate the shortcut.
/// Generated locally, so the bundle carries no quarantine xattr and opens
/// without a Gatekeeper prompt.
enum ShortcutGenerator {
    /// Creates "<name>.app" in `directory`, replacing any existing one of the
    /// same name. Returns the bundle URL.
    @discardableResult
    static func createApp(
        named name: String,
        plan: GameLauncher.LaunchPlan,
        in directory: URL
    ) throws -> URL {
        let fm = FileManager.default
        let safeName = sanitizedFileName(name)
        let appURL = directory.appending(path: "\(safeName).app", directoryHint: .isDirectory)
        try? fm.removeItem(at: appURL)

        let macOS = appURL.appending(path: "Contents/MacOS", directoryHint: .isDirectory)
        do {
            try fm.createDirectory(at: macOS, withIntermediateDirectories: true)
            try infoPlist(name: safeName).write(
                to: appURL.appending(path: "Contents/Info.plist"),
                atomically: true, encoding: .utf8
            )
            let exec = macOS.appending(path: "launch")
            try launchScript(plan: plan).write(to: exec, atomically: true, encoding: .utf8)
            try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: exec.path)
        } catch {
            throw ShortcutError.writeFailed(error.localizedDescription)
        }
        return appURL
    }

    /// POSIX-sh script: export the plan's env over the inherited shell
    /// environment (matching `ProcessRunner`'s merge), then `exec` Wine. The
    /// `exec` makes Wine *become* this process so the bundle stays "running"
    /// for the game's lifetime.
    static func launchScript(plan: GameLauncher.LaunchPlan) -> String {
        var lines = [
            "#!/bin/sh",
            "# Generated by Fable. Launches this game with its bottle's Wine + environment.",
            "# A snapshot — re-create it from Fable if the bottle's backend or paths change.",
            "",
        ]
        for key in plan.environment.keys.sorted() {
            lines.append("export \(key)=\(shellQuote(plan.environment[key]!))")
        }
        lines.append("")
        lines.append("cd \(shellQuote(plan.workingDirectory.path))")
        let argv = ([plan.wine.path] + plan.wineArguments).map(shellQuote).joined(separator: " ")
        lines.append("exec \(argv) >> \(shellQuote(plan.logFile.path)) 2>&1")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// Single-quotes a string for sh, escaping embedded single quotes.
    static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    /// Strips characters illegal in a macOS filename.
    static func sanitizedFileName(_ name: String) -> String {
        let invalid = CharacterSet(charactersIn: "/:\\?%*|\"<>")
        let cleaned = name.components(separatedBy: invalid).joined(separator: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return cleaned.isEmpty ? "Fable Game" : cleaned
    }

    private static func infoPlist(name: String) -> String {
        """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleName</key><string>\(xmlEscape(name))</string>
            <key>CFBundleDisplayName</key><string>\(xmlEscape(name))</string>
            <key>CFBundleIdentifier</key><string>com.fable.shortcut.\(bundleSuffix(name))</string>
            <key>CFBundleExecutable</key><string>launch</string>
            <key>CFBundlePackageType</key><string>APPL</string>
            <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
            <key>CFBundleVersion</key><string>1.0</string>
            <key>CFBundleShortVersionString</key><string>1.0</string>
            <key>LSMinimumSystemVersion</key><string>12.0</string>
        </dict>
        </plist>
        """
    }

    private static func bundleSuffix(_ name: String) -> String {
        let allowed = CharacterSet.alphanumerics
        let mapped = name.unicodeScalars.map { allowed.contains($0) ? Character($0) : "-" }
        let joined = String(mapped).lowercased()
        return joined.isEmpty ? "game" : joined
    }

    private static func xmlEscape(_ value: String) -> String {
        value.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }
}
