import Foundation
import Testing
@testable import Fable

@Suite struct LocalizationTests {
    @Test
    func englishStringsBundleLoads() {
        // Bundle.module is generated by SwiftPM only when the package
        // declares resources — proves the .lproj setup is wired up.
        let bundle = Bundle.module
        let path = bundle.path(forResource: "Localizable", ofType: "strings")
        #expect(path != nil, "Localizable.strings missing from Bundle.module")
    }

    @Test
    func l10nReturnsEnglishCopyForKnownKey() {
        // Test runner runs in en — should resolve sidebar.bottles → "Bottles".
        let bottles = L10n.string("sidebar.bottles")
        #expect(bottles == "Bottles")
    }

    @Test
    func l10nFallsBackToKeyForMissingString() {
        // Missing keys must surface visibly during development —
        // mirrors SwiftUI's behavior.
        let result = L10n.string("does.not.exist.key")
        #expect(result == "does.not.exist.key")
    }

    @Test
    func l10nInterpolatesPositionalArgument() {
        let formatted = L10n.string("toast.bottle.duplicated", "MyBottle")
        #expect(formatted.contains("MyBottle"))
    }

    @Test
    func spanishLprojDirectoryExists() {
        let bundle = Bundle.module
        let spanish = bundle.path(forResource: "Localizable", ofType: "strings", inDirectory: nil, forLocalization: "es")
        #expect(spanish != nil, "Spanish localization not bundled — check Package.swift resources")
    }

    @Test
    func spanishTranslationLoadsThroughExplicitBundle() throws {
        let bundle = Bundle.module
        guard let path = bundle.path(
            forResource: "Localizable", ofType: "strings",
            inDirectory: nil, forLocalization: "es"
        ), let dict = NSDictionary(contentsOfFile: path) as? [String: String] else {
            Issue.record("Spanish strings file unreadable")
            return
        }
        #expect(dict["sidebar.bottles"] == "Botellas")
        #expect(dict["bottle.list.create"] == "Crear botella")
    }

    @Test
    func appSectionTitleResolvesThroughL10n() {
        // AppSection.title now goes through L10n; an en runner should
        // get the English copy back.
        #expect(AppSection.bottles.title == "Bottles")
        #expect(AppSection.bottles.localizationKey == "sidebar.bottles")
    }
}
